name: wt_skillmeter
description:  War Thunder Skill Meter 2

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+200

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #State management
  provider: ^6.0.3
  #Firebase
  firebase_core: ^1.19.2 
  cloud_firestore: ^3.3.0
  firebase_auth: ^3.4.2
  firebase_crashlytics: ^2.8.5
  #Sign-In
  google_sign_in: ^5.4.0
  sign_in_with_apple: ^4.0.0
  crypto: ^3.0.2
  #Ads
  google_mobile_ads: ^1.3.0
  app_tracking_transparency: ^2.0.2+4
  #Icons
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0
  #Syncfusion
  syncfusion_flutter_gauges: ^20.2.38
  #Feedback screen
  package_info_plus: ^1.4.2
  device_info_plus: ^4.0.0
  url_launcher: ^6.1.5
  in_app_review: ^2.0.4
  share_plus: ^4.0.10
  #Miscellaneous
  introduction_screen: ^3.0.2
  persistent_bottom_nav_bar: ^4.0.2
  intl: ^0.17.0
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  http: ^0.13.4
  html: ^0.15.0
  webview_flutter: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.5
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/icon.png
  fullscreen: true
  android: true
  ios: true

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
